### ISSUE TITLE
runners_token returns null

### ISSUE THREAD

**Issue by nmoreau-ocl** [theapsgroup/steampipe-plugin-gitlab#16]
To reproduce run the following query 

```
> select
  path,runners_token
from
  gitlab_group
```

Using the same token I can access the runner registration token using the api so the problem appears to be with the gitlab plugin  
`curl --fail  --header "Private-Token: ${GITLAB_TOKEN}" "https://$URL/api/v4/groups/$id"`

**Comment by graza-io** [comment]
Hey @nmoreau-ocl 

Thanks for the report, I can confirm this is indeed the case. It seems to stem from the underlying SDK used returning an empty string for the `group.RunnersToken` property regardless of the value being in the API call.

I will check to see if this has been remediated in a newer version of the GitLab SDK & if so update accordingly.

**Comment by graza-io** [comment]
I've checked with latest release of the SDK [v0.73.1](https://github.com/xanzy/go-gitlab/releases/tag/v0.73.1) and this still currently returns empty string for the RunnersToken property of a group when called by the `ListGroups` function, but returns it based on the `GetGroup` function.

I've created an issue over on their repo: [here](https://github.com/xanzy/go-gitlab/issues/1534)

**Comment by graza-io** [comment]
For now (as a temporary workaround) - you can obtain the `runners_token` by simple querying for a specific group:
```sql
select path, runners_token from gitlab_group where ID = 123;
```

This should return your required value.

**Comment by nmoreau-ocl** [comment]
Great news, thank you

**Comment by e-gineer** [comment]
Hey @graza-io ... for List APIs that don't include all the get information, one approach is to use a Hydrate function to do the sub-API call to the GET for those affected columns.

Pro - This makes the list behave identically to the get commands in terms of the per-row data.

Con - You do a get call per row (if those columns are requested in the query).

**Comment by graza-io** [comment]
> Hey @graza-io ... for List APIs that don't include all the get information, one approach is to use a Hydrate function to do the sub-API call to the GET for those affected columns.
> 
> Pro - This makes the list behave identically to the get commands in terms of the per-row data.
> 
> Con - You do a get call per row (if those columns are requested in the query).

Yup, that's a potential band-aid, would be interesting to see why the SDK drops this value for the List approach, when it's actually there in the returned JSON payload from the API.
