### ISSUE TITLE
Add table gitlab_group_hook

### ISSUE THREAD

**Issue by khushboo9024** [theapsgroup/steampipe-plugin-gitlab#21]
We require gitlab_group_hook table for our compliance mod, please let us know if there are any plans to add this table.

Reference:
https://pkg.go.dev/github.com/xanzy/go-gitlab@v0.55.0#GroupsService.ListGroupHooks

**Comment by graza-io** [comment]
Added to current draft PR: https://github.com/theapsgroup/steampipe-plugin-gitlab/pull/27 (will be adding more tables to this PR before review/merge)

**Comment by khushboo9024** [comment]
Hey @graza-io , Thank you so much for working on this so quickly. We really appreciate it. Please let us know if any help is needed on this table (or others) from our side. We're happy to contribute.

Thanks!
