### ISSUE TITLE
Add table gitlab_notification_setting 

### ISSUE THREAD

**Issue by khushboo9024** [theapsgroup/steampipe-plugin-gitlab#22]
We require gitlab_notification_setting table for our compliance mod, please let us know if there are any plans to add this table.

Reference:
https://pkg.go.dev/github.com/xanzy/go-gitlab@v0.73.1#NotificationSettingsService.GetGlobalSettings

**Comment by graza-io** [comment]
This API endpoint doesn't return anything of any real value...

On-Prem
```shell
❯ curl --header "PRIVATE-TOKEN: [censored]" "https://gitlab.[censored].com/api/v4/notification_settings"
{"level":"participating","notification_email":"[censored]@[censored].com"}
```

Public Cloud
```shell
❯ curl --header "PRIVATE-TOKEN: [censored]" "https://gitlab.com/api/v4/notification_settings"
{"level":"participating","notification_email":"[censored]@[censored].io"}
```

Therefore I don't think it's worth the investment in adding this particular table.
