### ISSUE TITLE
Typo in docs/index.md

### ISSUE THREAD

**Issue by hampusadamsson** [theapsgroup/steampipe-plugin-gitlab#29]
Typo on row 40 in docs/index.md 
`~./steampipe/config/gitlab.spc` -> `~/.steampipe/config/gitlab.spc`

**Comment by graza-io** [comment]
Thanks, fixed in https://github.com/theapsgroup/steampipe-plugin-gitlab/commit/372a11c7dc5fa5c00fbc29530667bad4618935aa
