### ISSUE TITLE
Set GITLAB_ADDR to gitlab.com by default

### ISSUE THREAD

**Issue by notwedtm** [theapsgroup/steampipe-plugin-gitlab#3]
Would it make sense to have this set by default? That would make those who have `GITLAB_TOKEN` already set in their environment for other reasons have an excellent OOB experience.

**Comment by graza-io** [comment]
Hi @notwedtm 

That's a good suggestion.

We're currently trying to iron-out a best approach for the "public" hosted GitLab, once we have satiated this, we'll move onto QoL improvements (where we'll discuss this option) before publishing it to the Steampipe Hub.
