### ISSUE TITLE
Expose GitLab CICD variables and their attributes in a Steampipe table

### ISSUE THREAD

**Issue by gc-eh** [theapsgroup/steampipe-plugin-gitlab#39]
Hello, I'd like to be able to check that sensitive variables are set to Protected in our CICD pipelines in GitLab, e.g. to ensure that production AWS AK/SK aren't exposed to developers. However the current plugin doesn't expose CICD variables and their attributes.

Would it be possible to add GitLab CICD variables and their attributes to a Steampipe table?

Thanks,
Guillaume

**Comment by graza-io** [comment]
@gc-eh - thanks for raising this, looks like it should be fairly trivial to create the desired features:

Proposal would be:
https://docs.gitlab.com/ee/api/project_level_variables.html -> `gitlab_project_variable` (key on project_id)
https://docs.gitlab.com/ee/api/group_level_variables.html -> `gitlab_group_variable` (key on group_id)
https://docs.gitlab.com/ee/api/instance_level_ci_variables.html -> `gitlab_instance_variable` (only available on self-hosted variants, will return empty results when used against gitlab.com itself)

**Comment by gc-eh** [comment]
This would be great. Thanks!
