### ISSUE TITLE
Querying gitlab_epic returns an error

### ISSUE THREAD

**Issue by chrisshaw** [theapsgroup/steampipe-plugin-gitlab#44]
![Screenshot from 2023-02-15 10-45-12](https://user-images.githubusercontent.com/2966918/219077689-48954e97-eae2-4813-b97e-b59f3b6f19e8.png)

## Environment

Steampipe Cloud

## To reproduce

1. Install the GitLab plugin from https://cloud.steampipe.io/user/<user>/create/connection
2. Query the `gitlab_epic` table. You do not need to include the `due_date` field that seems to cause the problem.
3. Observe error `ERROR: rpc error: code = Unknown desc = interfaceToColumnValue failed for column 'due_date': cannot convert 2022-12-16 to a time.Time (SQLSTATE HV000)`

**Comment by graza-io** [comment]
I'll take a look at this at some point this week, thanks for the report @chrisshaw

**Comment by graza-io** [comment]
This will be published shortly as `v0.2.2` - however I don't know how long it'll take to be available on Steampipe Cloud.

**Comment by chrisshaw** [comment]
Appreciate your responsiveness!

**Comment by misraved** [comment]
@chrisshaw @graza-io the latest version of the `gitlab` plugin (v0.2.2) has been published to the hub and marked for an update on steampipe cloud over the weekend 👍.

Thanks @chrisshaw for pointing out the issue and thanks @graza-io for the quick fix 👍.
