### ISSUE TITLE
Is `epic_issue_id` expected to be blank?

### ISSUE THREAD

**Issue by chrisshaw** [theapsgroup/steampipe-plugin-gitlab#47]
I'm unsure if I'm running into a me problem or an issue with the plugin, sorry. Am I doing something wrong below?

Our group is on the GitLab Ultimate plan. That said, we're getting it as part of an OSS sponsorship. From my understanding, we should be able to access the [`epic`](https://docs.gitlab.com/ee/api/issues.html#single-issue) object from the REST API. 

I have some issues with known epics. Let's use [this one](https://gitlab.com/groups/upchieve/-/epics/209) as an example. 

![Screenshot from 2023-02-27 20-08-24](https://user-images.githubusercontent.com/2966918/221726016-def28679-89e3-4226-8133-17bb833e8df4.png)

Note the issues [high-line#18](https://gitlab.com/upchieve/application/high-line/-/issues/18) and [subway#1247](https://gitlab.com/upchieve/subway/-/issues/1247).

When I go to query `gitlab_issue.epic_issue_id`, however, the [epic_issue_id](https://github.com/theapsgroup/steampipe-plugin-gitlab/blob/a6dc0f10481f882188adfebe6b6a68fe784ffac6/gitlab/table_issue.go#L478) comes back as `NULL`.

Below you can see a few issues, including high-line#18 and subway#1247 coming back as `NULL`.

![Screenshot from 2023-02-27 20-06-50](https://user-images.githubusercontent.com/2966918/221725904-66463aa5-abe0-4b36-a0c1-2f67a09eb07d.png)

**Comment by chrisshaw** [comment]
No problem. I'm not seeing the field `epic_issue_id`. What you'll notice is a couple other epic-related fields: `epic_iid` (which docs say is deprecated) and the nested object `epic`.

Here's an example issue that came bace with an epic.

<details>
<summary>Response sample</summary>

```
  {
    "id": 123398678,
    "iid": 1248,
    "project_id": 23285197,
    "title": "Add PDF Scripts to Videos",
    "description": "Add PDF scripts to videos for UPchieve 101. They can be linked by adding the link to the `videoPDF` property [here](https://gitlab.com/upchieve/subway/-/merge_requests/1227/diffs#809a4d9d4453f515e56ba0413370f94acd0c372a_34_36) for a given material\n\nThe scripts are still being worked on\n\n## Tasks\n- [ ] Code review\n- [ ] Staging smoke tests\n- [ ] Merge to main\n- [ ] Deploy to prod\n\n## Smoke tests\n- [ ] Student/volunteer can login\n- [ ] Student/volunteer can make/join session\n- [ ] Student/volunteer can use whiteboard and chat in session",
    "state": "opened",
    "created_at": "2023-02-09T21:31:37.458Z",
    "updated_at": "2023-02-09T21:34:02.177Z",
    "closed_at": null,
    "closed_by": null,
    "labels": [
      "Blocked",
      "team:: staff",
      "type::user feature"
    ],
    "milestone": null,
    "assignees": [],
    "author": {
      "id": 7303103,
      "username": "treystevens",
      "name": "Trey Stevens",
      "state": "active",
      "avatar_url": "https://gitlab.com/uploads/-/system/user/avatar/7303103/avatar.png",
      "web_url": "https://gitlab.com/treystevens"
    },
    "type": "ISSUE",
    "assignee": null,
    "user_notes_count": 0,
    "merge_requests_count": 0,
    "upvotes": 0,
    "downvotes": 0,
    "due_date": null,
    "confidential": false,
    "discussion_locked": null,
    "issue_type": "issue",
    "web_url": "https://gitlab.com/upchieve/subway/-/issues/1248",
    "time_stats": {
      "time_estimate": 0,
      "total_time_spent": 0,
      "human_time_estimate": null,
      "human_total_time_spent": null
    },
    "task_completion_status": {
      "count": 7,
      "completed_count": 0
    },
    "weight": null,
    "blocking_issues_count": 0,
    "has_tasks": false,
    "_links": {
      "self": "https://gitlab.com/api/v4/projects/23285197/issues/1248",
      "notes": "https://gitlab.com/api/v4/projects/23285197/issues/1248/notes",
      "award_emoji": "https://gitlab.com/api/v4/projects/23285197/issues/1248/award_emoji",
      "project": "https://gitlab.com/api/v4/projects/23285197",
      "closed_as_duplicate_of": null
    },
    "references": {
      "short": "#1248",
      "relative": "#1248",
      "full": "upchieve/subway#1248"
    },
    "severity": "UNKNOWN",
    "moved_to_id": null,
    "service_desk_reply_to": null,
    "epic_iid": 206,
    "epic": {
      "id": 626565,
      "iid": 206,
      "title": "UPchieve 101 version 1.5",
      "url": "/groups/upchieve/-/epics/206",
      "group_id": 10007222,
      "human_readable_end_date": "Dec 16, 2022",
      "human_readable_timestamp": "<strong>Past due</strong>"
    },
    "iteration": null,
    "health_status": null
  },
```

</details>

**Comment by graza-io** [comment]
Yup, the `epic_issue_id` field can be returned on the object but seemingly not from all issue obtaining endpoints so yes in this instance it's not really a bug but how the GitLab API is designed.

I'll add in the fields in the embedded `epic` object in `v0.3.0` of the plugin. This'll be tracked on https://github.com/theapsgroup/steampipe-plugin-gitlab/issues/48
