### ISSUE TITLE
query on gitlab_project returns error "....call for table 'gitlab_project' is missing 2 required quals..."

### ISSUE THREAD

**Issue by dmeilinger-webpt** [theapsgroup/steampipe-plugin-gitlab#55]
Attempting query 

`select * from gitlab_project` 

returns the following error.

`[HV000] ERROR: rpc error: code = Internal desc = 'List' call for table 'gitlab_project' is missing 2 required quals: column:'owner_id' operator: = column:'owner_username' operator: =`

Querying by known project_id works fine. 

`select * from gitlab_project where id=XXX`

Am I missing a config somewhere?  Updated to latest plugin (0.4.1)

Thanks !

**Comment by graza-io** [comment]
Hey @dmeilinger-webpt 

Firstly are you using hosted GitLab or on-Premise?

A bit of what is happening under the hood:

The difference is the level of operation that's being performed, when an `id` is provided, it's simply a direct `Get` operation to obtain a singular item.

When attempting to list out Projects, we don't want to iterate every possible project on GitLab SaaS:
a) It would take an awfully long time.
b) You're likely to get rate-limited many many times over.

Therefore the `List` operation requires either an `owner_id` or an `owner_username` to obtain a reasonable subset of projects - I also find it strange the error says missing 2 as it's an `AnyOf` (so actually only one of them is required).

**Comment by dmeilinger-webpt** [comment]
Hi, thanks for the quick follow up!  This is on-prem Gitlab.   I understand completely the design decision to scope the request to those parameters to narrow the dataset.  I guess what is confusing is that the first example [SteamPipe plugins documentation](https://hub.steampipe.io/plugins/theapsgroup/gitlab/tables/gitlab_project)  doesn't use the either of those parameters. so my expectation was that a simple select * would work.  If this is by design, please feel free to close this =)

**Comment by graza-io** [comment]
For on-prem I think it should be fine to allow for obtaining every project. 

In fact I believe that was the initial intention. 

I'll leave this open for now and loop round into why it's not behaving quite right when I have a bit of time to dig in.

**Comment by graza-io** [comment]
@dmeilinger-webpt if you're comfortable building from source, I've created a branch for a potential fix for this issue (which should allow you to list all projects for an on-prem instance).

Branch: [issue-55](https://github.com/theapsgroup/steampipe-plugin-gitlab/tree/issue-55)

Instructions for local testing:
- Ensure no running instances of Steampipe: `pkill -f steampipe` (or whichever similar command is supported in your env)
- Clone repo: `git clone https://github.com/theapsgroup/steampipe-plugin-gitlab.git`
- Checkout branch: `git checkout issue-55`
- Build: `make`
- Test: `steampipe query "select * from gitlab_project"`

Expected output is that this lists all projects for your on-prem instance.

**Comment by dmeilinger-webpt** [comment]
Works great!  Thanks for the quick fix!

**Comment by e-gineer** [comment]
Hey @graza-io ... suggest we update the docs to be clear on which queries are expected to work in on-prem vs saas?
