### ISSUE TITLE
Getting events

### ISSUE THREAD

**Issue by lyda** [theapsgroup/steampipe-plugin-gitlab#57]
The gitlab events api is useful for assessing the performance of an individual developer or a team or to compare projects.

I'd be interested in implementing this, but curious what people thing about how it should work. And if people would want it.

Option 1 would be to have a `gitlab_events` table and if `user_id` isn't specified in a where clause, just get the logged in user's events.  If it is, get that/those `user_id`'s events.

Option 2 would have two tables: `gitlab_my_events` for the logged in user and `gitlab_user_events` with a requirement that `user_id` must be specified in a where clause.

Option 2 seems idiomatically correct based on the [existing tables](https://hub.steampipe.io/plugins/theapsgroup/gitlab/tables).

**Comment by graza-io** [comment]
Hey @lyda - thanks for the interest!

You're correct, option 2 (`gitlab_my_events` & `gitlab_user_events`) would be the way to differentiate those.

Useful link(s) for getting started on table development: https://steampipe.io/docs/develop/writing-your-first-table#references

Can't wait to see this come to fruition!

**Comment by lyda** [comment]
Thanks.  Yep, have a window with a bunch of references - and also have the plugin-sdk cloned. I find `git grep` an easier way to hunt down functions/types sometimes.

I'm always amused how go-gitlab and go-git sometimes seem equally complex.

**Comment by graza-io** [comment]
@lyda - thanks for all your work here, it's appreciated!

I've merged this into the `main` branch for now & will be releasing in next published release!

**Comment by lyda** [comment]
It was fun. And helps me. But I'll look at doing some more bits as I go.
